---
- name: Install Kubernetes with Containerd
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb is defined and ansible_swaptotal_mb > 0
      ignore_errors: yes

    - name: Remove swap entry from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^/.*swap.*'
        replace: ''
      when: ansible_swaptotal_mb is defined and ansible_swaptotal_mb > 0
      ignore_errors: yes

    - name: Load br_netfilter kernel module
      command: modprobe br_netfilter

    - name: Set kernel parameters for Kubernetes
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        reload: yes
      loop:
        - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
        - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
        - { name: "net.ipv4.ip_forward", value: "1" }

    - name: Install Containerd dependencies
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
        update_cache: yes
      
    - name: Add Containerd apt-key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
      
    - name: Add Containerd apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
      
    - name: Install Containerd
      apt:
        name: "containerd.io"
        state: present
        update_cache: yes

    - name: Configure Containerd
      copy:
        content: "{{ lookup('file', 'containerd-config.toml') }}"
        dest: /etc/containerd/config.toml
      
    - name: Restart Containerd
      systemd:
        name: containerd
        state: restarted

    - name: Add Kubernetes apt-key
      apt_key:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - kubeadm
        - kubelet
        - kubectl